name: Test
on: [push, pull_request]

jobs:
  ut:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn test --coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage/